Repository AY2021S1-CS2113-T14-2/tp, pull requests merged in 2020-11, with the labels that each got.

#160 Fix bugs related to null question during semi-one-line add command
  .gitignore
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/deck/FlashCard.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
Labels: priority.High, severity.High, type.Bug, type.Task

#163 add GameEngine, GameParser, GameStorage tests
  docs/team/alwaysnacy.md
  docs/team/kaijiel24.md
  docs/team/wangwaynesg.md
  src/main/java/seedu/ecardnomics/game/GameEngine.java
  src/main/java/seedu/ecardnomics/parser/GameParser.java
  src/test/java/seedu/ecardnomics/game/GameEngineTest.java
  src/test/java/seedu/ecardnomics/game/GameStorageTest.java
  src/test/java/seedu/ecardnomics/parser/DeckParserTest.java
  src/test/java/seedu/ecardnomics/parser/GameParserTest.java
  src/test/java/seedu/ecardnomics/parser/NormalParserTest.java
Labels: priority.Medium, severity.Medium, type.Task

#166 update Commands, Game Mode sections, add Exceptions section to DG
  docs/DeveloperGuide.md
  docs/images-dg/DG-Design-Commands-Breakdown.png
  docs/images-dg/DG-Design-Commands-UML.png
  docs/images-dg/DG-Design-Commands.png
  docs/images-dg/DG-Exceptions-Architecture.png
  docs/images-dg/DG-Game-Mode-Architecture-Overview.png
  docs/images-dg/DG-Game-Mode-Sequence.png
  docs/images-dg/DG-Game-Storage-Game-Engine.png
  docs/images-dg/DG-Game-Use-Case.png
  docs/images-dg/DG-run-game-loop-sd.png
  docs/images-dg/Game-Mode-Design.png
  docs/images-dg/Game-Mode-Sequence.png
  docs/team/zhixiangteoh.md
Labels: priority.High, type.Bug, type.Guide, type.Task

#167 update PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/zhixiangteoh.md
  docs/team/zhixiangteoh.png
Labels: type.Guide

#165 Update UG and DG according to feedback.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images-dg/PP-Sequence.png
Labels: type.Guide, type.Task

#169 update DG with class and method font styles, update PPP
  docs/DeveloperGuide.md
  docs/team/zhixiangteoh.md
Labels: priority.High, type.Guide

#170 shorten PPP UG and DG extracts
  docs/team/zhixiangteoh.md
Labels: type.Guide

#171 fix bug where entering just punctuation as answer leads to 100.0 score
  data/deckList.txt
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/exceptions/NoAlphaNumericInputException.java
  src/main/java/seedu/ecardnomics/game/GameEngine.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
  src/test/java/seedu/ecardnomics/game/GameEngineTest.java
  src/test/java/seedu/ecardnomics/parser/DeckParserTest.java
Labels: priority.High, severity.High, type.Bug, type.Task

#172 Pretty Printing in Game Mode and Log to File
  .gitignore
  src/main/java/seedu/ecardnomics/Main.java
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
  src/main/java/seedu/ecardnomics/parser/GameParser.java
  src/main/java/seedu/ecardnomics/parser/NormalParser.java
  src/main/java/seedu/ecardnomics/storage/LogStorage.java
  src/test/java/seedu/ecardnomics/command/deck/ListCommandTest.java
Labels: severity.Medium, type.Task

#173 cut PPP UG and DG extracts images
  docs/team/zhixiangteoh.md
Labels: type.Guide

#176 Fix index out of bounds error when -cs option is used
  src/main/java/seedu/ecardnomics/exceptions/BothOcAndCsException.java
  src/main/java/seedu/ecardnomics/powerpoint/PowerPoint.java
Labels: type.Bug

#180 User Guide updates
  docs/UserGuide.md
Labels: type.Guide

#182 Updates to UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/LiewWS.md
Labels: type.Guide

#207 Update pptx, fix delete force y output, increase dash line to 80 char and update UG and tests to reflect changes
  data/deckList.txt
  docs/UserGuide.md
  docs/images-ug/PPTX-Default-Color-Schemes.png
  docs/images-ug/PPTX-Example.png
  docs/team/kaijiel24.md
  pptx/Micro-Economics.pptx
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/command/deck/DeleteCommand.java
  src/main/java/seedu/ecardnomics/command/normal/PowerPointCommand.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
  src/main/java/seedu/ecardnomics/parser/NormalParser.java
  src/main/java/seedu/ecardnomics/powerpoint/ColorOption.java
  src/main/java/seedu/ecardnomics/powerpoint/PowerPoint.java
  src/test/java/seedu/ecardnomics/UiTest.java
  src/test/java/seedu/ecardnomics/command/deck/ListCommandTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Enhancement

#209 fix FlashCard test case
  src/test/java/seedu/ecardnomics/deck/FlashCardTest.java
Labels: priority.High, type.Bug

#210 Update UG and DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images-dg/DG-Exceptions-Architecture.png
  src/main/java/seedu/ecardnomics/parser/NormalParser.java
Labels: type.Guide

#213 Resolve Game Mode pretty print, Help commands pretty print, corresponding UG sections
  data/deckList.txt
  docs/UserGuide.md
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/command/deck/HelpCommand.java
  src/main/java/seedu/ecardnomics/command/game/HelpCommand.java
  src/main/java/seedu/ecardnomics/command/normal/HelpCommand.java
  src/main/java/seedu/ecardnomics/game/Game.java
  src/main/java/seedu/ecardnomics/game/GameEngine.java
Labels: priority.High, severity.High, type.Guide, type.Task

#214 Add Storage check for non-alphanumeric question and answer.
  data/deckList.txt
  src/main/java/seedu/ecardnomics/deck/DeckList.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
  src/main/java/seedu/ecardnomics/storage/Storage.java
Labels: priority.High

#215 Fix issues discovered during meeting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/command/deck/HelpCommand.java
  src/main/java/seedu/ecardnomics/command/normal/DecksCommand.java
  src/main/java/seedu/ecardnomics/exceptions/EmptyQnAException.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
  src/test/java/seedu/ecardnomics/UiTest.java
  src/test/java/seedu/ecardnomics/parser/DeckParserTest.java
Labels: type.Bug, type.Guide, type.Task

#217 add deque to glossary
  docs/DeveloperGuide.md
Labels: type.Guide

#220 add game mode manual testing instructions
  docs/DeveloperGuide.md
Labels: type.Guide

#223 Update UG with information regarding editing the save data file
  docs/UserGuide.md
Labels: priority.Medium

#229 Update Storage format read and write
  data/deckList.txt
  docs/UserGuide.md
  src/main/java/seedu/ecardnomics/storage/Storage.java
Labels: priority.Medium

#222 Update pptx DG, glossary, manual testing, and JUnit Tests
  README.md
  docs/DeveloperGuide.md
  docs/images-dg/PPTX Sequence Diagram.png
  docs/images-dg/PPTX-Color-Options-Sequence-Diagram.png
  docs/team/kaijiel24.md
  docs/team/kaijiel24.png
  src/main/java/seedu/ecardnomics/command/normal/PowerPointCommand.java
  src/main/java/seedu/ecardnomics/parser/NormalParser.java
  src/main/java/seedu/ecardnomics/powerpoint/PowerPoint.java
  src/test/java/seedu/ecardnomics/parser/DeckParserTest.java
  src/test/java/seedu/ecardnomics/parser/NormalParserTest.java
Labels: type.Guide, type.Task

#230 Updated PPP and DG
  docs/DeveloperGuide.md
  docs/images-dg/DG-Exceptions-Architecture.png
  docs/images-dg/PPTX Sequence Diagram.png
  docs/team/kaijiel24.md
Labels: type.Guide

#227 Fix broken links and update version number
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/liewws.png
  src/main/java/seedu/ecardnomics/Main.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
Labels: type.Bug, type.Guide

#232 Update PPP
  docs/team/kaijiel24.md
Labels: type.Guide

#233 update PPP link
  docs/team/zhixiangteoh.md
Labels: type.Guide

#235 update toc dg ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Guide

#239 Fix pptx deck mode bug
  docs/DeveloperGuide.md
  docs/images-dg/DG-Exceptions-Architecture.png
  docs/images-ug/PPTX-Example.png
  docs/team/kaijiel24.md
  src/main/java/seedu/ecardnomics/Ui.java
  src/main/java/seedu/ecardnomics/exceptions/InvalidPptxArgumentException.java
  src/main/java/seedu/ecardnomics/parser/DeckParser.java
  src/main/java/seedu/ecardnomics/parser/NormalParser.java
  src/test/java/seedu/ecardnomics/parser/DeckParserTest.java
Labels: type.Bug

#241 Update DG diagram
  docs/images-dg/PPTX-Color-Options-Sequence-Diagram.png
Labels: type.Guide

#242 fix white bg images
  docs/images-dg/DG-Design-Model.png
  docs/images-dg/PP-Sequence.png
Labels: type.Bug, type.Guide

#243 fixes #237, fixes #244
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Bug, type.Guide
